const WINING_NUMBER_0F_CORRECT_ANSWERS = 3;
const YES_OR_NO = {
    YES: 'yes',
    NO: 'no',
};

const MATH_OPERATION = [
    '-',
    '*',
    '+',
];

const PRIME_NUMBERS_BEFORE_100 = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
];

const ARITHMETIC_PROGRESSION_HIDE_ELEMENT_STRING = '..';
const MAX_NUMBER_OF_ELEMENTS_IN_PROGRESSION = 10;
const LENGTH_OF_PROGRESSION = 9;
const MAX_VALUE_OF_RANDOM_NUMBER = 100;
const RADIX = 10;

export {
    WINING_NUMBER_0F_CORRECT_ANSWERS,
    YES_OR_NO,
    MATH_OPERATION,
    PRIME_NUMBERS_BEFORE_100,
    ARITHMETIC_PROGRESSION_HIDE_ELEMENT_STRING,
    MAX_NUMBER_OF_ELEMENTS_IN_PROGRESSION,
    LENGTH_OF_PROGRESSION,
    MAX_VALUE_OF_RANDOM_NUMBER,
    RADIX,
};
