const WINING_NUMBER_0F_CORRECT_ANSWERS = 3;
const YES_OR_NO = {
    YES: 'yes',
    NO: 'no',
};

const MATH_OPERATION = [
    '-',
    '*',
    '+',
];

const ARITHMETIC_PROGRESSION_HIDE_ELEMENT_STRING = '..';
const MAX_NUMBER_OF_ELEMENTS_IN_PROGRESSION = 10;
const LENGTH_OF_PROGRESSION = 9;
const MAX_VALUE_OF_RANDOM_NUMBER = 100;

export {
    WINING_NUMBER_0F_CORRECT_ANSWERS,
    YES_OR_NO,
    MATH_OPERATION,
    ARITHMETIC_PROGRESSION_HIDE_ELEMENT_STRING,
    MAX_NUMBER_OF_ELEMENTS_IN_PROGRESSION,
    LENGTH_OF_PROGRESSION,
    MAX_VALUE_OF_RANDOM_NUMBER,
};
