const WINING_NUMBER_0F_CORRECT_ANSWERS = 3;
const EVEN_GAME_POSSIBLE_USER_ANSWERS = {
    YES: 'yes',
    NO: 'no',
};

export {
    WINING_NUMBER_0F_CORRECT_ANSWERS,
    EVEN_GAME_POSSIBLE_USER_ANSWERS,
};
